 ## Data Mining and Machine Learning
 ## Feature Engineering: Feature Discretization(Binning)
 ### Edgar Acuna
 ####  Enero 2019

In [17]:
import pandas as pd
import numpy as np
from sklearn import preprocessing 
from sklearn.preprocessing import KBinsDiscretizer
import Orange

In [18]:
#Leyendo el dataset wine de la UCI
#wine_data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")
wine_data=pd.read_csv("c://PW-PR/winequality-red.csv", sep=";")
wine_data.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [19]:
wine_data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

#### Eliminating the last column(classes)

In [20]:
df=wine_data.drop('quality',axis=1)

###  Equal-width Discretization using KBinsDiscretizer from Scikit-learn

#### Binning each column of the data in 10 values using equal width bins

In [21]:
est = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
est.fit(df)  

Xt = est.transform(df)
Xt

array([[2., 3., 0., ..., 6., 1., 1.],
       [2., 5., 0., ..., 3., 2., 2.],
       [2., 4., 0., ..., 4., 1., 2.],
       ...,
       [1., 2., 1., ..., 5., 2., 4.],
       [1., 3., 1., ..., 6., 2., 2.],
       [1., 1., 4., ..., 5., 1., 4.]])

In [22]:
#Converting the array into dataframe
tempodf=pd.DataFrame(Xt)
tempodf.columns=df.columns
tempodf.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,2.794872,2.299562,2.304565,0.563477,0.833021,1.552220,0.955597,4.405253,4.010632,1.458412,2.656035
std,1.562370,1.266570,1.877786,1.023903,0.838832,1.514922,1.161504,1.419380,1.240942,1.040778,1.666654
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,3.000000,1.000000,1.000000
50%,2.000000,2.000000,2.000000,0.000000,1.000000,1.000000,1.000000,4.000000,4.000000,1.000000,2.000000
75%,4.000000,3.000000,4.000000,1.000000,1.000000,2.000000,1.000000,5.000000,5.000000,2.000000,4.000000
max,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

### Equal  width Discretization using my own program

In [23]:
wine_data.columns.tolist()

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [24]:
def disc_col_ew(df,str,k,out):
    df1=df[str]
    bins=np.linspace(df1.min(), df1.max(),k)
    if out=="num":
        df1=pd.cut(df1,bins=bins,include_lowest=True, right=True,labels=False)
    else:
        bins[0]=float('-inf')
        bins[k-1]=float('inf')
        df1=pd.cut(df1,bins=bins,include_lowest=True, right=True)  
    return df1

In [25]:
disc_col_ew(wine_data,'citric acid',10,out="num")

0       0
1       0
2       0
3       5
4       0
5       0
6       0
7       0
8       0
9       3
10      0
11      3
12      0
13      2
14      1
15      1
16      5
17      2
18      0
19      4
20      4
21      2
22      1
23      0
24      1
25      1
26      2
27      1
28      0
29      0
       ..
1569    1
1570    4
1571    1
1572    2
1573    1
1574    7
1575    3
1576    5
1577    1
1578    1
1579    0
1580    2
1581    0
1582    0
1583    2
1584    3
1585    3
1586    3
1587    0
1588    2
1589    1
1590    1
1591    0
1592    1
1593    0
1594    0
1595    0
1596    1
1597    1
1598    4
Name: citric acid, Length: 1599, dtype: int64

In [26]:
def disc_ew(df,k,out):
    name=df.columns.tolist()
    disc=pd.DataFrame()
    for name in df.columns.tolist():
        disc[name]=disc_col_ew(df,name,k,out)
    return disc

In [27]:
disc_ew(wine_data,10,out="symb")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,"(7.111, 8.367]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.998, 0.999]","(3.446, 3.587]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
1,"(7.111, 8.367]","(0.769, 0.931]","(-inf, 0.111]","(2.522, 4.144]","(0.0786, 0.145]","(24.667, 32.556]","(37.444, 68.889]","(0.996, 0.998]","(3.163, 3.304]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
2,"(7.111, 8.367]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(37.444, 68.889]","(0.996, 0.998]","(3.163, 3.304]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
3,"(10.878, 12.133]","(-inf, 0.282]","(0.556, 0.667]","(-inf, 2.522]","(-inf, 0.0786]","(16.778, 24.667]","(37.444, 68.889]","(0.998, 0.999]","(3.022, 3.163]","(0.516, 0.701]","(9.122, 9.844]","(5.778, 6.333]"
4,"(7.111, 8.367]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.998, 0.999]","(3.446, 3.587]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
5,"(7.111, 8.367]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(37.444, 68.889]","(0.998, 0.999]","(3.446, 3.587]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
6,"(7.111, 8.367]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(37.444, 68.889]","(0.996, 0.998]","(3.163, 3.304]","(-inf, 0.516]","(9.122, 9.844]","(4.667, 5.222]"
7,"(7.111, 8.367]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.993, 0.995]","(3.304, 3.446]","(-inf, 0.516]","(9.844, 10.567]","(6.889, 7.444]"
8,"(7.111, 8.367]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.996, 0.998]","(3.304, 3.446]","(0.516, 0.701]","(9.122, 9.844]","(6.889, 7.444]"
9,"(7.111, 8.367]","(0.444, 0.607]","(0.333, 0.444]","(5.767, 7.389]","(-inf, 0.0786]","(16.778, 24.667]","(100.333, 131.778]","(0.998, 0.999]","(3.304, 3.446]","(0.701, 0.887]","(9.844, 10.567]","(4.667, 5.222]"
10,"(5.856, 7.111]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(37.444, 68.889]","(0.995, 0.996]","(3.163, 3.304]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
11,"(7.111, 8.367]","(0.444, 0.607]","(0.333, 0.444]","(5.767, 7.389]","(-inf, 0.0786]","(16.778, 24.667]","(100.333, 131.778]","(0.998, 0.999]","(3.304, 3.446]","(0.701, 0.887]","(9.844, 10.567]","(4.667, 5.222]"
12,"(-inf, 5.856]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(37.444, 68.889]","(0.993, 0.995]","(3.446, 3.587]","(0.516, 0.701]","(9.844, 10.567]","(4.667, 5.222]"
13,"(7.111, 8.367]","(0.607, 0.769]","(0.222, 0.333]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.996, 0.998]","(3.163, 3.304]","(1.443, 1.629]","(-inf, 9.122]","(4.667, 5.222]"
14,"(8.367, 9.622]","(0.607, 0.769]","(0.111, 0.222]","(2.522, 4.144]","(0.145, 0.212]","(48.333, 56.222]","(131.778, 163.222]","(0.998, 0.999]","(3.022, 3.163]","(0.701, 0.887]","(9.122, 9.844]","(4.667, 5.222]"
15,"(8.367, 9.622]","(0.607, 0.769]","(0.111, 0.222]","(2.522, 4.144]","(0.145, 0.212]","(48.333, 56.222]","(131.778, 163.222]","(0.998, 0.999]","(3.163, 3.304]","(0.887, 1.072]","(9.122, 9.844]","(4.667, 5.222]"
16,"(8.367, 9.622]","(-inf, 0.282]","(0.556, 0.667]","(-inf, 2.522]","(0.0786, 0.145]","(32.556, 40.444]","(100.333, 131.778]","(0.996, 0.998]","(3.163, 3.304]","(0.701, 0.887]","(9.844, 10.567]","(6.889, 7.444]"
17,"(7.111, 8.367]","(0.444, 0.607]","(0.222, 0.333]","(-inf, 2.522]","(0.345, 0.411]","(8.889, 16.778]","(37.444, 68.889]","(0.996, 0.998]","(3.022, 3.163]","(1.258, 1.443]","(9.122, 9.844]","(4.667, 5.222]"
18,"(7.111, 8.367]","(0.444, 0.607]","(-inf, 0.111]","(4.144, 5.767]","(0.0786, 0.145]","(-inf, 8.889]","(-inf, 37.444]","(0.996, 0.998]","(3.304, 3.446]","(-inf, 0.516]","(-inf, 9.122]","(3.556, 4.111]"
19,"(7.111, 8.367]","(0.282, 0.444]","(0.444, 0.556]","(-inf, 2.522]","(0.278, 0.345]","(16.778, 24.667]","(37.444, 68.889]","(0.996, 0.998]","(3.022, 3.163]","(1.072, 1.258]","(9.122, 9.844]","(5.778, 6.333]"
20,"(8.367, 9.622]","(-inf, 0.282]","(0.444, 0.556]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(37.444, 68.889]","(0.996, 0.998]","(3.304, 3.446]","(0.516, 0.701]","(9.122, 9.844]","(5.778, 6.333]"
21,"(7.111, 8.367]","(0.282, 0.444]","(0.222, 0.333]","(-inf, 2.522]","(0.0786, 0.145]","(16.778, 24.667]","(68.889, 100.333]","(0.998, 0.999]","(3.446, 3.587]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
22,"(7.111, 8.367]","(0.282, 0.444]","(0.111, 0.222]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.996, 0.998]","(3.163, 3.304]","(0.887, 1.072]","(9.122, 9.844]","(4.667, 5.222]"
23,"(8.367, 9.622]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(37.444, 68.889]","(0.996, 0.998]","(3.163, 3.304]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
24,"(5.856, 7.111]","(0.282, 0.444]","(0.111, 0.222]","(-inf, 2.522]","(0.0786, 0.145]","(16.778, 24.667]","(37.444, 68.889]","(0.996, 0.998]","(3.304, 3.446]","(0.516, 0.701]","(9.122, 9.844]","(5.778, 6.333]"
25,"(5.856, 7.111]","(0.282, 0.444]","(0.111, 0.222]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.995, 0.996]","(3.304, 3.446]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
26,"(7.111, 8.367]","(0.282, 0.444]","(0.222, 0.333]","(-inf, 2.522]","(0.0786, 0.145]","(-inf, 8.889]","(-inf, 37.444]","(0.996, 0.998]","(3.163, 3.304]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
27,"(7.111, 8.367]","(0.282, 0.444]","(0.111, 0.222]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.996, 0.998]","(3.163, 3.304]","(0.887, 1.072]","(9.122, 9.844]","(4.667, 5.222]"
28,"(5.856, 7.111]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.996, 0.998]","(3.446, 3.587]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
29,"(7.111, 8.367]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(-inf, 8.889]","(-inf, 37.444]","(0.996, 0.998]","(3.304, 3.446]","(0.516, 0.701]","(9.122, 9.844]","(5.778, 6.333]"
...,...,...,...,...,...,...,...,...,...,...,...,...
1569,"(5.856, 7.111]","(0.444, 0.607]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.993, 0.995]","(3.446, 3.587]","(0.516, 0.701]","(11.289, 12.011]","(5.778, 6.333]"
1570,"(5.856, 7.111]","(0.282, 0.444]","(0.444, 0.556]","(-inf, 2.522]","(0.212, 0.278]","(16.778, 24.667]","(-inf, 37.444]","(0.993, 0.995]","(3.304, 3.446]","(0.887, 1.072]","(12.011, 12.733]","(5.778, 6.333]"
1571,"(5.856, 7.111]","(0.282, 0.444]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.995, 0.996]","(3.304, 3.446]","(0.516, 0.701]","(10.567, 11.289]","(5.778, 6.333]"
1572,"(7.111, 8.367]","(0.607, 0.769]","(0.222, 0.333]","(-inf, 2.522]","(-inf, 0.0786]","(32.556, 40.444]","(100.333, 131.778]","(0.996, 0.998]","(3.304, 3.446]","(-inf, 0.516]","(9.122, 9.844]","(4.667, 5.222]"
1573,"(5.856, 7.111]","(0.444, 0.607]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(37.444, 68.889]","(0.995, 0.996]","(3.446, 3.587]","(0.516, 0.701]","(12.011, 12.733]","(5.778, 6.333]"
1574,"(-inf, 5.856]","(0.282, 0.444]","(0.778, 0.889]","(13.878, inf]","(-inf, 0.0786]","(16.778, 24.667]","(68.889, 100.333]","(0.996, 0.998]","(3.304, 3.446]","(-inf, 0.516]","(9.844, 10.567]","(5.778, 6.333]"
1575,"(7.111, 8.367]","(0.444, 0.607]","(0.333, 0.444]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.995, 0.996]","(3.163, 3.304]","(0.516, 0.701]","(11.289, 12.011]","(5.778, 6.333]"
1576,"(7.111, 8.367]","(0.282, 0.444]","(0.556, 0.667]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.995, 0.996]","(3.163, 3.304]","(0.701, 0.887]","(10.567, 11.289]","(5.778, 6.333]"
1577,"(5.856, 7.111]","(0.607, 0.769]","(0.111, 0.222]","(4.144, 5.767]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.996, 0.998]","(3.446, 3.587]","(0.516, 0.701]","(11.289, 12.011]","(5.778, 6.333]"
1578,"(5.856, 7.111]","(0.607, 0.769]","(0.111, 0.222]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.995, 0.996]","(3.304, 3.446]","(0.516, 0.701]","(11.289, 12.011]","(5.778, 6.333]"
1579,"(5.856, 7.111]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(16.778, 24.667]","(-inf, 37.444]","(0.993, 0.995]","(3.446, 3.587]","(0.516, 0.701]","(11.289, 12.011]","(4.667, 5.222]"
1580,"(7.111, 8.367]","(0.282, 0.444]","(0.222, 0.333]","(-inf, 2.522]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.995, 0.996]","(3.304, 3.446]","(0.516, 0.701]","(11.289, 12.011]","(5.778, 6.333]"
1581,"(5.856, 7.111]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(16.778, 24.667]","(-inf, 37.444]","(0.993, 0.995]","(3.446, 3.587]","(0.516, 0.701]","(11.289, 12.011]","(4.667, 5.222]"
1582,"(5.856, 7.111]","(0.607, 0.769]","(-inf, 0.111]","(2.522, 4.144]","(-inf, 0.0786]","(8.889, 16.778]","(-inf, 37.444]","(0.993, 0.995]","(3.446, 3.587]","(-inf, 0.516]","(11.289, 12.011]","(4.667, 5.222]"
1583,"(5.856, 7.111]","(0.444, 0.607]","(0.222, 0.333]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(68.889, 100.333]","(0.995, 0.996]","(3.304, 3.446]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
1584,"(5.856, 7.111]","(0.282, 0.444]","(0.333, 0.444]","(-inf, 2.522]","(-inf, 0.0786]","(16.778, 24.667]","(-inf, 37.444]","(0.995, 0.996]","(3.163, 3.304]","(0.701, 0.887]","(11.289, 12.011]","(6.889, 7.444]"
1585,"(7.111, 8.367]","(0.282, 0.444]","(0.333, 0.444]","(2.522, 4.144]","(-inf, 0.0786]","(16.778, 24.667]","(37.444, 68.889]","(0.995, 0.996]","(3.163, 3.304]","(0.701, 0.887]","(11.289, 12.011]","(5.778, 6.333]"
1586,"(7.111, 8.367]","(0.282, 0.444]","(0.333, 0.444]","(-inf, 2.522]","(-inf, 0.0786]","(32.556, 40.444]","(37.444, 68.889]","(0.995, 0.996]","(3.304, 3.446]","(0.701, 0.887]","(11.289, 12.011]","(5.778, 6.333]"
1587,"(-inf, 5.856]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(16.778, 24.667]","(-inf, 37.444]","(0.995, 0.996]","(3.446, 3.587]","(0.516, 0.701]","(10.567, 11.289]","(5.778, 6.333]"
1588,"(7.111, 8.367]","(0.607, 0.769]","(0.222, 0.333]","(-inf, 2.522]","(-inf, 0.0786]","(32.556, 40.444]","(100.333, 131.778]","(0.993, 0.995]","(3.163, 3.304]","(0.701, 0.887]","(12.733, 13.456]","(5.778, 6.333]"
1589,"(5.856, 7.111]","(0.607, 0.769]","(0.111, 0.222]","(7.389, 9.011]","(-inf, 0.0786]","(24.667, 32.556]","(68.889, 100.333]","(0.998, 0.999]","(3.163, 3.304]","(0.516, 0.701]","(9.122, 9.844]","(4.667, 5.222]"
1590,"(5.856, 7.111]","(0.444, 0.607]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(-inf, 37.444]","(0.993, 0.995]","(3.304, 3.446]","(0.701, 0.887]","(11.289, 12.011]","(5.778, 6.333]"
1591,"(-inf, 5.856]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(8.889, 16.778]","(-inf, 37.444]","(0.993, 0.995]","(3.587, 3.728]","(0.516, 0.701]","(11.289, 12.011]","(5.778, 6.333]"
1592,"(5.856, 7.111]","(0.444, 0.607]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(37.444, 68.889]","(0.995, 0.996]","(3.304, 3.446]","(0.701, 0.887]","(10.567, 11.289]","(5.778, 6.333]"
1593,"(5.856, 7.111]","(0.607, 0.769]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(37.444, 68.889]","(0.996, 0.998]","(3.304, 3.446]","(0.701, 0.887]","(9.122, 9.844]","(5.778, 6.333]"
1594,"(5.856, 7.111]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(0.0786, 0.145]","(24.667, 32.556]","(37.444, 68.889]","(0.995, 0.996]","(3.446, 3.587]","(0.516, 0.701]","(9.844, 10.567]","(4.667, 5.222]"
1595,"(5.856, 7.111]","(0.444, 0.607]","(-inf, 0.111]","(-inf, 2.522]","(-inf, 0.0786]","(32.556, 40.444]","(37.444, 68.889]","(0.995, 0.996]","(3.446, 3.587]","(0.701, 0.887]","(10.567, 11.289]","(5.778, 6.333]"
1596,"(5.856, 7.111]","(0.444, 0.607]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(37.444, 68.889]","(0.995, 0.996]","(3.304, 3.446]","(0.701, 0.887]","(10.567, 11.289]","(5.778, 6.333]"
1597,"(5.856, 7.111]","(0.607, 0.769]","(0.111, 0.222]","(-inf, 2.522]","(-inf, 0.0786]","(24.667, 32.556]","(37.444, 68.889]","(0.995, 0.996]","(3.446, 3.587]","(0.701, 0.887]","(9.844, 10.567]","(4.667, 5.222]"
1598,"(5.856, 7.111]","(0.282, 0.444]","(0.444, 0.556]","(2.522, 4.144]","(-inf, 0.0786]","(16.778, 24.667]","(37.444, 68.889]","(0.995, 0.996]","(3.304, 3.446]","(0.516, 0.701]","(10.567, 11.289]","(5.778, 6.333]"

### Equal width discretization using Orange

In [28]:
veh = Orange.data.Table("c://PW-PR//vehicle.tab")
disc = Orange.preprocess.Discretize()
disc.method = Orange.preprocess.discretize.EqualWidth(n=10)
veh_disc = disc(veh)
print("Original dataset:")
for e in veh[:3]:
    print(e)

print("Discretized dataset:")
for e in veh_disc[:3]:
    print(e)

Original dataset:
[95, 48, 83, 178, 72, 10, 162, 42, 20, 159, 176, 379, 184, 70, 6, 16, 187, 197 | van]
[91, 41, 84, 141, 57, 9, 149, 45, 19, 143, 170, 330, 158, 72, 9, 14, 189, 199 | van]
[104, 50, 106, 209, 66, 10, 207, 32, 23, 158, 223, 635, 220, 73, 14, 9, 188, 196 | saab]
Discretized dataset:
[91 - 96, 46 - 49, 76 - 83, 173 - 196, 65 - 74, 7 - 13, 158 - 173, 40 - 44, 19 - 21, 153 - 160, 168 - 187, 351 - 434, 173 - 188, 67 - 74, 4 - 7, 12 - 16, 185 - 188, 196 - 199 | van]
[87 - 91, 41 - 43, 83 - 90, 127 - 150, 56 - 65, 7 - 13, 143 - 158, 44 - 47, 18 - 19, 139 - 146, 168 - 187, 267 - 351, 157 - 173, 67 - 74, 9 - 11, 12 - 16, 188 - 191, 199 - 202 | van]
[101 - 105, 49 - 51, ≥ 105, 196 - 218, 65 - 74, 7 - 13, 204 - 219, 30 - 33, 23 - 24, 153 - 160, 206 - 225, 601 - 684, 204 - 220, 67 - 74, 13 - 15, 8 - 12, 188 - 191, 196 - 199 | saab]

###  Equal Frequency Discretization using scikit-learn

In [29]:
est = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
est.fit(df)  
Xt = est.transform(df)
Xt

array([[3., 8., 0., ..., 9., 2., 1.],
       [4., 9., 0., ..., 2., 6., 3.],
       [4., 9., 1., ..., 3., 6., 3.],
       ...,
       [0., 4., 3., ..., 7., 7., 7.],
       [0., 7., 2., ..., 9., 7., 5.],
       [0., 1., 8., ..., 7., 6., 7.]])

In [30]:
#Converting the array into dataframe
tempodf=pd.DataFrame(Xt)
tempodf.columns=df.columns
tempodf.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,4.615385,4.574109,4.555972,4.722326,4.621639,4.707317,4.561601,4.517824,4.586617,4.609131,4.629769
std,2.848980,2.882445,2.867838,2.829170,2.859682,2.750927,2.837669,2.872253,2.860082,2.876984,2.856697
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
75%,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
max,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

### Equal frequency Discretization using Orange

In [31]:
disc = Orange.preprocess.Discretize()
disc.method = Orange.preprocess.discretize.EqualFreq(n=10)
veh1_disc = disc(veh)
print("Original dataset:")
for e in veh[:3]:
    print(e)

print("Discretized dataset:")
for e in veh1_disc[:3]:
    print(e)

Original dataset:
[95, 48, 83, 178, 72, 10, 162, 42, 20, 159, 176, 379, 184, 70, 6, 16, 187, 197 | van]
[91, 41, 84, 141, 57, 9, 149, 45, 19, 143, 170, 330, 158, 72, 9, 14, 189, 199 | van]
[104, 50, 106, 209, 66, 10, 207, 32, 23, 158, 223, 635, 220, 73, 14, 9, 188, 196 | saab]
Discretized dataset:
[94 - 98, 46 - 48, 80 - 84, 166 - 178, ≥ 70, 10 - 10, 158 - 168, 38 - 42, 20 - 20, 156 - 162, 174 - 180, 362 - 414, 182 - 190, 68 - 70, 6 - 8, 14 - 16, 186 - 188, 196 - 198 | van]
[90 - 92, 40 - 42, 80 - 84, 136 - 146, 56 - 58, 8 - 10, 142 - 150, 44 - 46, 18 - 20, 140 - 144, 170 - 174, 326 - 340, 156 - 166, 72 - 72, 8 - 10, 14 - 16, 188 - 190, 198 - 200 | van]
[102 - 106, 48 - 52, ≥ 104, 200 - 212, 64 - 66, 10 - 10, 188 - 208, 32 - 34, 22 - 24, 156 - 162, 222 - 228, 524 - 636, ≥ 218, 72 - 74, ≥ 12, 8 - 10, 188 - 188, 194 - 196 | saab]

### MDLP-Entropy Discretization using Orange

In [32]:
disc = Orange.preprocess.Discretize()
disc.method = Orange.preprocess.EntropyMDL(force=False)
veh1_disc = disc(veh)
print("Original dataset:")
for e in veh[:3]:
    print(e)

print("Discretized dataset:")
for e in veh1_disc[:3]:
    print(e)

Original dataset:
[95, 48, 83, 178, 72, 10, 162, 42, 20, 159, 176, 379, 184, 70, 6, 16, 187, 197 | van]
[91, 41, 84, 141, 57, 9, 149, 45, 19, 143, 170, 330, 158, 72, 9, 14, 189, 199 | van]
[104, 50, 106, 209, 66, 10, 207, 32, 23, 158, 223, 635, 220, 73, 14, 9, 188, 196 | saab]
Discretized dataset:
[88 - 98, 40 - 50, 76 - 92, 176 - 234, 68 - 86, 8 - 16, 154 - 164, 42 - 44, 20 - 20, 148 - 160, 166 - 180, 348 - 390, 170 - 192, 64 - 74, < 12, < 18, 186 - 192, ≥ 190 | van]
[88 - 98, 40 - 50, 76 - 92, < 176, 52 - 68, 8 - 16, 140 - 154, 44 - 46, 18 - 20, 136 - 148, 166 - 180, 298 - 348, < 170, 64 - 74, < 12, < 18, 186 - 192, ≥ 190 | van]
[≥ 104, 50 - 54, ≥ 92, 176 - 234, 52 - 68, 8 - 16, 164 - 230, 30 - 42, 20 - 26, 148 - 160, 180 - 242, 581 - 722, 192 - 242, 64 - 74, ≥ 12, < 18, 186 - 192, ≥ 190 | saab]